"""Ticket MCP tool contract (S-L4-SCREENPOP) — the product interface.

Single source of truth for the contract shared by the built-in server
(`api.mcp_server.tools.tickets`), the platform handoff client
(`api.services.pipecat.transfer_context_handoff`), and the conformance
runner. Owner deployments replace the *server*, never this contract:
a wrapper implementing the REQUIRED tools is drop-in swappable with the
agent side unchanged (C5).

Versioning is additive-only: new optional fields/tools may be added under
the same major version; nothing existing is renamed, removed, or
re-typed. Unknown fields must be tolerated (or the request rejected as a
whole) — never dynamically stored.
"""

from typing import Any

CONTRACT_VERSION = "1.0"

# Tools a server MUST implement for the transfer handoff write path.
REQUIRED_TOOLS = ("create_ticket", "append_ticket_note")
# Tools used by screen-pop readers; a missing one degrades lookup, not writes.
OPTIONAL_TOOLS = ("get_ticket", "find_tickets_by_caller")

# --- Error envelope -------------------------------------------------------

ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"  # bad input; retrying won't help
ERROR_NOT_FOUND = "NOT_FOUND"  # unknown ticket / foreign-org ticket (indistinguishable)
ERROR_UNAVAILABLE = "UNAVAILABLE"  # transient backend failure; retry may help

ERROR_CODES = (ERROR_VALIDATION_FAILED, ERROR_NOT_FOUND, ERROR_UNAVAILABLE)


def error_envelope(code: str, message: str, retryable: bool) -> dict:
    """The contract's uniform failure shape, returned as the tool result."""
    return {"error": {"code": code, "message": message, "retryable": retryable}}


def is_error(result: Any) -> bool:
    return isinstance(result, dict) and "error" in result


# --- Field constraints ----------------------------------------------------

# Correlation key carried in REFER headers; generated by the platform, never
# by the caller. Deterministic per workflow run so retries reproduce it.
TICKET_ID_PREFIX = "CS-"
TICKET_ID_MAX_LEN = 64

# E.164 is "+" plus up to 15 digits; empty string = anonymous caller.
CALLER_NUMBER_MAX_LEN = 20
ROOM_NAME_MAX_LEN = 128
TRANSFER_REASON_MAX_LEN = 64
NOTE_CONTENT_MAX_LEN = 4000
FIND_TICKETS_DEFAULT_LIMIT = 5
FIND_TICKETS_MAX_LIMIT = 20

NOTE_TYPES = ("summary", "transfer_failed", "generic")

# Fixed summary schema — the LLM only fills values, never adds fields.
# `verified_identity` is copied from deterministic verification state
# (C6): "verified" | "unverified" | "unknown". Everything else is LLM
# narrative and must be treated as untrusted by readers.
SUMMARY_FIELDS = (
    "intent",
    "verified_identity",
    "steps_done",
    "pending",
    "transfer_reason",
)
VERIFIED_IDENTITY_VALUES = ("verified", "unverified", "unknown")
SUMMARY_TEXT_MAX_LEN = 500
SUMMARY_LIST_MAX_ITEMS = 20


def ticket_id_for_run(workflow_run_id: int) -> str:
    """Deterministic ticket id for a workflow run (idempotency by construction)."""
    return f"{TICKET_ID_PREFIX}{workflow_run_id}"
